// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUiyY1Wvi5MUWDXXNg9wJWxllc7Sct8wM',
    appId: '1:1046811852767:web:6044824f2151efbddb8e6a',
    messagingSenderId: '1046811852767',
    projectId: 'transformers-builders',
    authDomain: 'transformers-builders.firebaseapp.com',
    storageBucket: 'transformers-builders.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMkQctn4pIeaxMRLwXQI7OIi3b62fV9Eo',
    appId: '1:1046811852767:android:fe3ed48da5be081ddb8e6a',
    messagingSenderId: '1046811852767',
    projectId: 'transformers-builders',
    storageBucket: 'transformers-builders.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZRZzpmrAD32nyG-hGO9MOY_VBHTej0Sk',
    appId: '1:1046811852767:ios:1570941bfe7f77a0db8e6a',
    messagingSenderId: '1046811852767',
    projectId: 'transformers-builders',
    storageBucket: 'transformers-builders.firebasestorage.app',
    iosBundleId: 'com.example.transformersBuilders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZRZzpmrAD32nyG-hGO9MOY_VBHTej0Sk',
    appId: '1:1046811852767:ios:1570941bfe7f77a0db8e6a',
    messagingSenderId: '1046811852767',
    projectId: 'transformers-builders',
    storageBucket: 'transformers-builders.firebasestorage.app',
    iosBundleId: 'com.example.transformersBuilders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUiyY1Wvi5MUWDXXNg9wJWxllc7Sct8wM',
    appId: '1:1046811852767:web:693a4d71b3c408a5db8e6a',
    messagingSenderId: '1046811852767',
    projectId: 'transformers-builders',
    authDomain: 'transformers-builders.firebaseapp.com',
    storageBucket: 'transformers-builders.firebasestorage.app',
  );
}
